version: '3.8'

services:
  db:
    container_name: 'dti-postgres'
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - dti-network
    volumes:
      - dti-postgres:/var/lib/postgresql/data

networks:
  dti-network:
    driver: bridge

volumes:
  dti-postgres:
